### ISSUE TITLE
Failed to compile the program. undefined reference to `gits::CMappedHandle::currentVersion_'

### ISSUE THREAD

**Issue by B5paper** [intel/gits#2]
I followed the building commands in `BUILDING.md` and got a compiling error:

```
...
[100%] Linking CXX executable gitsPlayer
[100%] Built target GitsRecorder
/usr/bin/ld: ../common/libcommon.a(argument.cpp.o): in function `gits::CMappedHandle::Read(gits::CBinIStream&)':
argument.cpp:(.text+0x19dd): undefined reference to `gits::CMappedHandle::currentVersion_'
collect2: error: ld returned 1 exit status
gmake[2]: *** [player/CMakeFiles/gitsPlayer.dir/build.make:178: player/gitsPlayer] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1065: player/CMakeFiles/gitsPlayer.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

System: Linux Ubuntu-2204 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

git repo commit: `f2e97348c54493746e4cd3012b38a9db9863b776`

**Comment by kszornak** [comment]
Hi. Thanks for reporting this issue. 
We fixed it in this commit: 430d435936131811096920e3b207c7815c70e8e6
Could you try to check if it helps on your side?

Best Regards,
Karol

**Comment by B5paper** [comment]
It works. Thank you very much.
This issue can be closed.

Best regards,
Liucheng

**Comment by AI-LJ** [comment]
good job
